### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by FrankMittelbach**
maining for testing pull request :-)

### CODE REVIEW

**Comment by u-fischer** [comment]
Hm. Ok. Which of the merge options should I use now? merge commit, squash and merge or rebase and merge?

**Comment by car222222** [comment]
So nothing to look at here?

**Comment by FrankMittelbach** [comment]
> So nothing to look at here?

not for you, no :-) The missing comma is something I know has to be here (English or not :-) )

**Comment by FrankMittelbach** [comment]
> Hm. Ok. Which of the merge options should I use now? merge commit, squash and merge or rebase and merge?

I hope we would find out ... me "no idea"  we may have to ask others

**Comment by wspr** [comment]
@FrankMittelbach — depends on your preference for git :) If the commits are all very clean I would recommend rebase. If the changes are relatively small and/or the commits are messy, I would recommend squash. If there are lots of development branches with lots of people, stuff is being moved in from everywhere, lots of branches around the place and so on, "merge" is good.

**Pull request merged**
